repos:
- repo: local
  hooks:
  - id: lint
    name: lint
    description: "Lint and sort"
    entry: make lint
    pass_filenames: false
    require_serial: true
    language: system
  - id: graphql
    name: graphql
    description: "Dump GraphQL schema"
    entry: python manage.py dump_graphql_schema
    pass_filesnames: false
    require_serial: true
    language: system
