ignore:
  - "**tests**/test_*.py"


beta_groups:
  - "labels"

flag_management:
  individual_flags:
    - name: "smart-labels"
      carryforward: true
      carryforward_mode: "labels"

codecov:
  require_ci_to_pass: false
