# Generated by Django 4.2.3 on 2023-10-31 06:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_auto_20231003_1342"),
        ("reports", "0010_alter_reportdetails_files_array_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reportsession",
                    ),
                ),
            ],
            options={
                "db_table": "reports_testsessions",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "reports_tests",
            },
        ),
    ]
