# Generated by Django 4.2.3 on 2023-10-31 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_testsession_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outcome", models.BooleanField()),
                ("duration", models.FloatField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="reports.test",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="reports.testsession",
                    ),
                ),
            ],
            options={
                "db_table": "reports_testruns",
            },
        ),
    ]
