# Generated by Django 4.2.3 on 2023-10-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_testrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsession",
            name="upload_file_type",
            field=models.CharField(default="coverage", max_length=100, null=True),
        ),
    ]
